/*

 CURSORTILE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char CursorSprite[] =
{
  0xDB,0x00,0x81,0x00,0x00,0x00,0x81,0x00,
  0x81,0x00,0x00,0x00,0x81,0x00,0xDB,0x00
};

/* End of CURSORTILE.C */
