/*

 KEYBOARDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Repo\gaming-monsters\lesson14\keyboard.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define KeyboardMapWidth 20
#define KeyboardMapHeight 18
#define KeyboardMapBank 0

extern unsigned char KeyboardMap[];

/* End of KEYBOARDMAP.H */
