/*

 LINKSPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char linkSprite[] =
{
  0x3E,0x00,0x27,0x40,0x8A,0x4A,0x22,0x40,
  0x34,0x41,0xE2,0x1D,0x3C,0x41,0x00,0x24
};

/* End of LINKSPRITE.C */
