/*

 ZELDASPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Zelda[] =
{
  0x6C,0x6C,0xFE,0x92,0xD6,0xAA,0xC6,0xBA,
  0x6C,0x54,0x38,0x28,0x10,0x10,0x00,0x00,
  0x1E,0x1E,0x22,0x22,0x4A,0x42,0x82,0x9E,
  0x84,0xFC,0x88,0xF8,0xF0,0xF0,0x00,0x00
};

/* End of ZELDASPRITES.C */
