/*

 ZELDAMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : D:\Repo\gaming-monsters\zeldahud\zelda-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define zeldaMapWidth 20
#define zeldaMapHeight 1
#define zeldaMapBank 0

unsigned char zeldaMap[] =
{
  0x00,0x0B,0x0A,0x0A,0x0A,0x00,0x0E,0x0E,0x0E,0x0C,
  0x0C,0x0C,0x0C,0x0C,0x0C,0x0C,0x0C,0x0C,0x0C,0x0C
};

/* End of ZELDAMAP.C */
