/*

 ZELDAMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : D:\Repo\gaming-monsters\zeldahud\zelda-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define zeldaMapWidth 20
#define zeldaMapHeight 1
#define zeldaMapBank 0

extern unsigned char zeldaMap[];

/* End of ZELDAMAP.H */
